version: '3.9'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: deepchief
      POSTGRES_PASSWORD: deepchief
      POSTGRES_DB: deepchief
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    environment:
      MINIO_ROOT_USER: deepchief
      MINIO_ROOT_PASSWORD: deepchiefsecret
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  api:
    build:
      context: ../
      dockerfile: services/api/Dockerfile
    env_file:
      - ../.env
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "8080:8080"
    volumes:
      - ../:/workspace

volumes:
  postgres_data:
  minio_data:


