name: Docker Build (main)

on:
  push:
    branches: [ main ]

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: services/api/Dockerfile
          push: false
          provenance: false
          tags: api:build
      - name: Build Console image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/console/Dockerfile
          push: false
          provenance: false
          tags: console:build


